openapi: 3.0.3
info:
  title: Task Manager API
  version: 1.0.0
  description: API para gestionar tareas del curso
servers:
  - url: http://localhost:3000/v1
paths:
  /tasks:
    get:
      summary: Listar todas las tareas
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          example: "abc123"
        title:
          type: string
          example: "Aprender OpenAPI"